# Darker QHD monitor: airy lavender glass
include kitty-common.conf

background #16131F
foreground #F7F1F6
background_opacity 0.50

active_tab_background #6E56AF
active_tab_foreground #F7F1F6
inactive_tab_background #2B2638
inactive_tab_foreground #B9AEE6
tab_bar_background #121019
